### ISSUE TITLE
Observing Service Worker Behaviour iOS

### ISSUE THREAD

**Issue by spencerdezartsmith** [inspectdev/inspect-issues#189]
I am trying out this Inspect tool in the hopes that I can have more visibility over the service worker and caches on iOS (PWA). When using any Chromium browser, I am able to see my service worker in action when I load my app as seen in the screenshot.

<img width="643" alt="Screenshot 2024-01-27 at 8 57 59 pm" src="https://github.com/inspectdev/inspect-issues/assets/17863697/29bacc37-9313-49a9-b938-9c4bfbf65bf0">

When I use Safari Technology Preview with a plugged in iOS device I can see nothing really. In the network tab I can see what I believe to the be the SW precache installing but I can't see any caches so its hard to say what is happening. 

In Inspect, I see the same inspect interface as Chrome/Brave but I don't see any Service Worker activity:

<img width="811" alt="Screenshot 2024-01-27 at 9 45 20 pm" src="https://github.com/inspectdev/inspect-issues/assets/17863697/df03fe68-8db3-43f4-a00d-296644f8b199">

<img width="754" alt="Screenshot 2024-01-27 at 9 44 29 pm" src="https://github.com/inspectdev/inspect-issues/assets/17863697/81e58265-9275-475a-bad6-21508c473d7c">

Is it something wrong on my end? Should I be able to see this using iOS device?

Thanks in advance!

**Comment by auchenberg** [comment]
@spencerdezartsmith Thanks for posting this issue!

Webkit and Inspect does not support "control" over the Service Worker like you are used to in Chrome, due to limited APIs by Apple, but you if you choose the Service Worker target like on your second screenshot, you can use inspect to debug the service worker javascript by going to the Scripts tab in Inspect and see the loaded files.
