### ISSUE TITLE
Unable to log-in/Allowing self-signed certificates

### ISSUE THREAD

**Issue by aldrashan** [inspectdev/inspect-issues#211]
Whatever I do, the application thinks I'm not logged in and I get the "Continue on inspect.dev" screen.
When I open the developer tools, I see the following error:
Uncaught (in promise) Error: request to https://inspect.dev/api/changelog failed, reason: self signed certificate in certificate chain.

I'm trying to use the application behind a corporate firewall, where certificates are replaced by a self-signed certificate.
Could this be the reason?
If so, how can I fix this?

**Comment by auchenberg** [comment]
Hi @aldrashan,

We are using https://clerk.dev/ as a auth provider, which needs to loads its components from their domain. Since you are replacing SSL certs, this is probably the reason for why the app fails to load, as we can't communicate to our API, and authenticate you.

We don't support self signed certificates at the moment, and probably never will as it would bypass the very security of our API.
