### ISSUE TITLE
Network: Only provisional headers are shown for network requests

### ISSUE THREAD

**Issue by auchenberg** [inspectdev/inspect-issues#92]
Only shows the provisional headers in the network tab for requests.

Seen on: Iphone 7 latest safari version)

**Comment by ghost** [comment]
When using Inspect to view network traffic it only shows provisional headers. I've tested this on multiple iOS devices and all are experiencing the same problem. This is pretty annoying because it's not showing me the full list of request headers, making it harder for me to inspect network traffic and manage to replicate it. Here is a image of what it's showing me:
![grafik](https://user-images.githubusercontent.com/82937328/132698674-f44702f2-7696-44b0-b36f-ee78e56c6e68.png)

Devices used:
iPhone 7, latest version
iPhone XS, latest version
iPad Air , latest version

**Comment by ghost** [comment]
Hello, any updates regarding this bug?
